/*
 * This source file was generated by the Gradle 'init' task
 */
package org.classifier

import org.classifier.modules.PrimeNumberProcessor

fun main() {
// Create a PrimeNumberProcessor for the first thousand numbers
    val processor = PrimeNumberProcessor(1..20)
    
    // Process the numbers
    val result = processor.processNumbers()
    
    // Print the results
    println("Prime numbers:")
    result.primes.forEach { it.printValue() }
    
    println("\nOdd numbers:")
    result.odds.forEach { it.printValue() }
    
    println("\nEven numbers:")
    result.evens.forEach { it.printValue() }
    
    // Print some statistics
    println("\nStatistics:")
    println("Total numbers processed: 20")
    println("Number of primes: ${result.primes.size}")
    println("Number of odds: ${result.odds.size}")
    println("Number of evens: ${result.evens.size}")
}
